name: Build & Deploy to k3s

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push MQTT Sound App
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mqtt-sound-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mqtt-sound-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to k3s via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K3S_SERVER }}
          username: ${{ secrets.K3S_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            kubectl rollout restart deployment mqtt-sound-app
